package core

import (
	"fmt"
	"math"
	"strings"
	"time"

	"github.com/siherrmann/slicer/model"
)

// GenerateGCode converts print paths into G-code for 3D printing.
// It handles: extrusion calculation, retraction, fan control, speed management,
// Z-hop, and layer-specific overrides (first layer speed, min layer time).
func GenerateGCode(paths []model.ContinuousPath, config model.SliceConfig) string {
	var sb strings.Builder

	// Header comments
	sb.WriteString("; Generated by Slicer\n")
	sb.WriteString(fmt.Sprintf("; Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("; Layer Height: %.2f mm\n", config.LayerHeight))
	sb.WriteString(fmt.Sprintf("; First Layer: %.2f mm\n", config.FirstLayer))
	sb.WriteString(fmt.Sprintf("; Nozzle Diameter: %.2f mm\n", config.NozzleDiameter))
	sb.WriteString(fmt.Sprintf("; Line Width: %.2f mm\n", config.LineWidth))
	sb.WriteString(fmt.Sprintf("; Infill Density: %.0f%%\n", config.InfillDensity*100))
	sb.WriteString(fmt.Sprintf("; Flow Multiplier: %.2f\n", config.FlowMultiplier))
	sb.WriteString("\n")

	// Start G-code
	sb.WriteString(config.StartGCode)
	sb.WriteString("\n")

	// State tracking
	var (
		totalE       float64 // Total extrusion distance
		currentZ     float64
		currentLayer int = -1
		retracted    bool
		fanOn        bool
		lastSpeed    float64
		lastX, lastY float64
		absoluteE    bool = true // Use absolute extrusion mode
	)

	// Set absolute extrusion mode
	sb.WriteString("M82 ; Absolute extrusion\n")
	sb.WriteString("G90 ; Absolute positioning\n\n")

	for _, path := range paths {
		for _, seg := range path.Segments {
			// Detect layer change by checking Z
			segZ := seg.Start.Z
			if segZ != currentZ && segZ > 0 {
				currentZ = segZ
				currentLayer++

				sb.WriteString(fmt.Sprintf("\n; Layer %d, Z = %.3f\n", currentLayer, currentZ))

				// Fan control based on FanOnLayer
				if !fanOn && currentLayer >= config.FanOnLayer {
					sb.WriteString(fmt.Sprintf("M106 S%d ; Fan on\n", config.FanSpeed))
					fanOn = true
				} else if currentLayer < config.FanOnLayer && fanOn {
					sb.WriteString("M107 ; Fan off\n")
					fanOn = false
				}

				// Move to layer Z
				sb.WriteString(fmt.Sprintf("G0 Z%.3f F%s\n", currentZ, speedToF(config.TravelSpeed)))
			}

			if seg.IsTravel {
				// Retract before travel if not already retracted
				if !retracted && config.RetractionDist > 0 {
					totalE -= config.RetractionDist
					sb.WriteString(fmt.Sprintf("G1 E%.5f F%s ; Retract\n", totalE, speedToF(config.RetractionSpeed)))

					// Z-hop
					if config.RetractionZHop > 0 {
						sb.WriteString(fmt.Sprintf("G0 Z%.3f ; Z-hop\n", currentZ+config.RetractionZHop))
					}
					retracted = true
				}

				// Travel move
				sb.WriteString(fmt.Sprintf("G0 X%.3f Y%.3f F%s\n",
					seg.End.X, seg.End.Y, speedToF(config.TravelSpeed)))

				lastX = seg.End.X
				lastY = seg.End.Y
			} else {
				// Un-retract before extrusion
				if retracted {
					// Remove Z-hop
					if config.RetractionZHop > 0 {
						sb.WriteString(fmt.Sprintf("G0 Z%.3f\n", currentZ))
					}

					// Prime (un-retract + extra prime)
					totalE += config.RetractionDist + config.RetractionPrime
					sb.WriteString(fmt.Sprintf("G1 E%.5f F%s ; Un-retract\n", totalE, speedToF(config.RetractionSpeed)))
					retracted = false
				}

				// Calculate extrusion amount
				segLength := segmentLength(seg)
				layerHeight := config.LayerHeight
				if currentLayer == 0 {
					layerHeight = config.FirstLayer
				}
				extrusionAmount := calculateExtrusion(segLength, config.LineWidth, layerHeight,
					config.NozzleDiameter, config.FlowMultiplier)
				totalE += extrusionAmount

				// Determine speed for this segment
				speed := getSegmentSpeed(seg, config, currentLayer)
				if speed != lastSpeed {
					lastSpeed = speed
				}

				// Extrusion move
				if absoluteE {
					sb.WriteString(fmt.Sprintf("G1 X%.3f Y%.3f E%.5f F%s\n",
						seg.End.X, seg.End.Y, totalE, speedToF(speed)))
				}

				lastX = seg.End.X
				lastY = seg.End.Y
			}
		}
	}

	// Suppress unused variable warnings
	_ = lastX
	_ = lastY

	sb.WriteString("\n")
	// End G-code
	sb.WriteString(config.EndGCode)

	return sb.String()
}

// calculateExtrusion computes the extrusion distance for a segment.
// Uses volumetric calculation: volume = length * width * height
// Then converts to filament length: E = volume / (π * (filament_d/2)²)
// Standard filament diameter is 1.75mm.
func calculateExtrusion(segLength, lineWidth, layerHeight, nozzleDiameter, flowMultiplier float64) float64 {
	filamentDiameter := 1.75 // mm — standard filament
	filamentArea := math.Pi * (filamentDiameter / 2.0) * (filamentDiameter / 2.0)

	// Cross-section area of the extruded line (approximate as rectangle)
	crossSection := lineWidth * layerHeight

	// Volume of material needed
	volume := crossSection * segLength

	// Convert to filament feed length
	e := (volume / filamentArea) * flowMultiplier

	return e
}

// getSegmentSpeed determines the appropriate speed for a segment
// based on its category and the current layer.
func getSegmentSpeed(seg model.PathSegment, config model.SliceConfig, layerIndex int) float64 {
	// Use per-segment speed if explicitly set
	if seg.Speed > 0 {
		speed := seg.Speed
		// First layer override
		if layerIndex == 0 && config.FirstLayerSpeed > 0 {
			speed = math.Min(speed, config.FirstLayerSpeed)
		}
		return math.Max(speed, config.MinSpeed)
	}

	// Determine speed from category
	var speed float64
	switch seg.Category {
	case model.CategoryOuterWall:
		speed = config.OuterShellSpeed
	case model.CategoryInnerWall:
		speed = config.WallSpeed
	case model.CategoryInfill:
		speed = config.InfillSpeed
	case model.CategorySolidInfill:
		speed = config.InfillSpeed * 0.8 // Slightly slower for solid infill
	case model.CategorySupport:
		speed = config.SupportSpeed
	case model.CategorySkirt, model.CategoryBrim:
		speed = config.WallSpeed
	default:
		speed = config.InfillSpeed
	}

	// First layer override
	if layerIndex == 0 && config.FirstLayerSpeed > 0 {
		speed = math.Min(speed, config.FirstLayerSpeed)
	}

	return math.Max(speed, config.MinSpeed)
}

// segmentLength calculates the XY length of a path segment (ignoring Z)
func segmentLength(seg model.PathSegment) float64 {
	dx := seg.End.X - seg.Start.X
	dy := seg.End.Y - seg.Start.Y
	return math.Sqrt(dx*dx + dy*dy)
}

// speedToF converts mm/s to F-value (mm/min) as a formatted string
func speedToF(mmPerSec float64) string {
	return fmt.Sprintf("%.0f", mmPerSec*60.0)
}
