package core

import (
	"strings"
	"testing"

	"github.com/siherrmann/slicer/model"
	"github.com/stretchr/testify/assert"
)

func TestSpeedToF(t *testing.T) {
	assert.Equal(t, "3600", speedToF(60.0))
	assert.Equal(t, "1500", speedToF(25.0))
	assert.Equal(t, "0", speedToF(0.0))
}

func TestSegmentLength(t *testing.T) {
	seg := model.PathSegment{
		Start: model.Vector3{X: 0, Y: 0},
		End:   model.Vector3{X: 3, Y: 4}, // 3-4-5 triangle
	}
	assert.Equal(t, 5.0, segmentLength(seg))

	seg2 := model.PathSegment{
		Start: model.Vector3{X: 10, Y: -5},
		End:   model.Vector3{X: 10, Y: -5}, // Zero length
	}
	assert.Equal(t, 0.0, segmentLength(seg2))
}

func TestGetSegmentSpeed(t *testing.T) {
	config := model.NewSliceConfig()
	config.FirstLayerSpeed = 20.0
	config.MinSpeed = 10.0
	config.OuterShellSpeed = 40.0
	config.WallSpeed = 50.0
	config.InfillSpeed = 60.0

	// Test category explicitly
	segWall := model.PathSegment{Category: model.CategoryInnerWall}
	assert.Equal(t, 50.0, getSegmentSpeed(segWall, *config, 1))

	// Test outer wall
	segOuter := model.PathSegment{Category: model.CategoryOuterWall}
	assert.Equal(t, 40.0, getSegmentSpeed(segOuter, *config, 1))

	// Test first layer override
	assert.Equal(t, 20.0, getSegmentSpeed(segOuter, *config, 0))

	// Test explicit segment speed
	segExplicit := model.PathSegment{Speed: 100.0}
	assert.Equal(t, 100.0, getSegmentSpeed(segExplicit, *config, 1))

	// Test explicit segment speed + first layer
	assert.Equal(t, 20.0, getSegmentSpeed(segExplicit, *config, 0))

	// Test min speed enforcement
	config.FirstLayerSpeed = 5.0
	assert.Equal(t, 10.0, getSegmentSpeed(segOuter, *config, 0))
}

func TestCalculateExtrusion(t *testing.T) {
	// segLength = 10, width = 0.4, height = 0.2 -> vol = 0.8
	// 1.75mm area = pi * (1.75/2)^2 ≈ 2.40528
	// e = 0.8 / 2.40528 ≈ 0.3326
	e := calculateExtrusion(10.0, 0.4, 0.2, 0.4, 1.0)
	assert.InDelta(t, 0.3326, e, 0.001)

	// Doubling flow multiplier
	e2 := calculateExtrusion(10.0, 0.4, 0.2, 0.4, 2.0)
	assert.InDelta(t, 0.6652, e2, 0.001)
}

func TestGenerateGCode(t *testing.T) {
	config := model.NewSliceConfig()
	config.LayerHeight = 0.2
	config.FirstLayer = 0.2
	config.FanOnLayer = 1
	config.StartGCode = "G28 ; home"
	config.EndGCode = "M104 S0 ; turn off temp"

	paths := []model.ContinuousPath{
		{
			Segments: []model.PathSegment{
				{Start: model.Vector3{X: 0, Y: 0, Z: 0.2}, End: model.Vector3{X: 10, Y: 0, Z: 0.2}, IsTravel: true},
				{Start: model.Vector3{X: 10, Y: 0, Z: 0.2}, End: model.Vector3{X: 10, Y: 10, Z: 0.2}, IsTravel: false},
			},
		},
		{
			Segments: []model.PathSegment{
				{Start: model.Vector3{X: 10, Y: 10, Z: 0.4}, End: model.Vector3{X: 0, Y: 10, Z: 0.4}, IsTravel: true},
				{Start: model.Vector3{X: 0, Y: 10, Z: 0.4}, End: model.Vector3{X: 0, Y: 0, Z: 0.4}, IsTravel: false},
			},
		},
	}

	gcode := GenerateGCode(paths, *config)

	// Check headers
	assert.Contains(t, gcode, "; Generated by Slicer")
	assert.Contains(t, gcode, "G28 ; home")
	assert.Contains(t, gcode, "M104 S0 ; turn off temp")

	// Check layers
	assert.Contains(t, gcode, "; Layer 0, Z = 0.200")
	assert.Contains(t, gcode, "; Layer 1, Z = 0.400")

	// Check fan
	assert.Contains(t, gcode, "M106") // Fan should turn on at layer 1 (Z=0.4)

	// Check that we see extrusions and travel moves correctly
	// Travel to 10,0
	assert.Contains(t, gcode, "X10.000 Y0.000")
	// Extrude to 10,10 with E value
	assert.Contains(t, gcode, "X10.000 Y10.000 E")

	// Check un-retract / retract (default config might have retraction = 0)
	// If retractions were > 0, we'd check for it. Let's make sure it doesn't crash.
	lines := strings.Split(gcode, "\n")
	assert.Greater(t, len(lines), 20)
}
