// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"github.com/siherrmann/slicer/model"
)

//go:embed viewer.js
var viewerJs string

func marshal(anyMap interface{}) string {
	jsonBytes, err := json.Marshal(anyMap)
	if err != nil {
		return "{}"
	}
	return string(jsonBytes)
}

// SlicerSidebar renders ONLY the sidebar + update scripts.
// HTMX swaps the outer container div, never the canvas.
func SlicerSidebar(bm *model.BaseModel, paths []model.ContinuousPath, config *model.SliceConfig) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"sidebar-container\" style=\"width: 320px; display: flex; flex-direction: column;\"><form id=\"slice-form\" hx-post=\"/slice\" hx-target=\"#sidebar-container\" hx-swap=\"outerHTML\" class=\"viewer-sidebar\" style=\"width: 100%; height: 100%; background: rgba(255,255,255,0.95); border-left: 1px solid #ddd; display: flex; flex-direction: column; box-shadow: -2px 0 10px rgba(0,0,0,0.1); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; z-index: 10;\"><div style=\"padding: 15px; border-bottom: 1px solid #ddd; background: #f8f9fa;\"><h2 style=\"margin: 0; font-size: 16px; color: #333;\">Slicer Einstellungen</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if bm != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div style=\"font-size: 11px; color: #666; margin-top: 4px;\">Modell: ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(bm.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 36, Col: 81}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div style=\"flex: 1; overflow-y: auto; padding: 15px;\"><!-- Ansicht & Analyse --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;\">Ansicht &amp; Analyse</label><div style=\"display: flex; gap: 5px; margin-bottom: 15px;\"><button type=\"button\" id=\"view-model-btn\" onclick=\"window.setViewMode('model')\" style=\"flex: 1; padding: 8px; border: 1px solid #ddd; background: #4CAF50; color: white; border-radius: 4px; cursor: pointer; font-size: 12px; transition: all 0.2s;\">Modell</button> <button type=\"button\" id=\"view-print-btn\" onclick=\"window.setViewMode('print')\" style=\"flex: 1; padding: 8px; border: 1px solid #ddd; background: white; color: #666; border-radius: 4px; cursor: pointer; font-size: 12px; transition: all 0.2s;\">Druck</button></div><label for=\"cut-slider\" style=\"display: block; font-size: 11px; color: #666; margin-bottom: 5px;\">Z-Schnitt (Vorschau)</label> <input type=\"range\" id=\"cut-slider\" min=\"0\" max=\"1\" step=\"0.001\" value=\"1\" style=\"width: 100%; margin-bottom: 5px;\" oninput=\"window.updateCutDepth(parseFloat(this.value))\"></div><!-- Layers & Shells --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Layers &amp; Shells</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Schichthöhe (mm)</label> <input type=\"number\" name=\"layer_height\" step=\"0.05\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", config.LayerHeight))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 56, Col: 106}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Erste Schicht</label> <input type=\"number\" name=\"first_layer\" step=\"0.05\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", config.FirstLayer))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 60, Col: 104}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Wandlinien (Count)</label> <input type=\"number\" name=\"shell_count\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.ShellCount))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 64, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Linienbreite</label> <input type=\"number\" name=\"line_width\" step=\"0.1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.LineWidth))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 68, Col: 101}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Wandreihenfolge</label> <select name=\"shell_order\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px; background: white;\"><option value=\"0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.ShellOrder == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, ">Innen → Außen</option> <option value=\"1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.ShellOrder == 1 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, ">Außen → Innen</option></select></div></div></div><!-- Infill --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Infill</label> <label style=\"display: block; font-size: 10px; color: #888;\">Dichte (%)</label> <input type=\"range\" name=\"infill_density\" min=\"0\" max=\"1\" step=\"0.01\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", config.InfillDensity))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 83, Col: 123}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" style=\"width: 100%; margin-bottom: 10px;\"><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Muster</label> <select name=\"infill_type\" style=\"width: 100%; padding: 6px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px; background: white;\"><option value=\"0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.InfillType == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, ">Lines</option> <option value=\"1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.InfillType == 1 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, ">Grid</option> <option value=\"2\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.InfillType == 2 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, ">Tri-Hexagon</option> <option value=\"5\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.InfillType == 5 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, ">Gyroid</option> <option value=\"4\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.InfillType == 4 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, ">Honeycomb</option></select></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Winkel (°)</label> <input type=\"number\" name=\"infill_angle\" step=\"5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.InfillAngle))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 97, Col: 103}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div></div></div><!-- Speeds --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Geschwindigkeit (mm/s)</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Infill</label> <input type=\"number\" name=\"infill_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.InfillSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 107, Col: 94}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Wände (innen)</label> <input type=\"number\" name=\"wall_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.WallSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 111, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Außenwand</label> <input type=\"number\" name=\"outer_shell_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.OuterShellSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 115, Col: 103}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Travel</label> <input type=\"number\" name=\"travel_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.TravelSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 119, Col: 94}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Erste Schicht</label> <input type=\"number\" name=\"first_layer_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 string
		templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.FirstLayerSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 123, Col: 103}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Minimum</label> <input type=\"number\" name=\"min_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.MinSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 127, Col: 88}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Flow Multiplikator</label> <input type=\"number\" name=\"flow_multiplier\" step=\"0.01\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", config.FlowMultiplier))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 131, Col: 112}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div></div></div><!-- Temperature & Cooling --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Temperatur &amp; Kühlung</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Nozzle (°C)</label> <input type=\"number\" name=\"nozzle_temp\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.NozzleTemp))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 141, Col: 92}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Bed (°C)</label> <input type=\"number\" name=\"bed_temp\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.BedTemp))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 145, Col: 86}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Lüfter (0-255)</label> <input type=\"number\" name=\"fan_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 string
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.FanSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 149, Col: 86}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Lüfter ab Layer</label> <input type=\"number\" name=\"fan_on_layer\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 string
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.FanOnLayer))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 153, Col: 91}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Min. Layerzeit (s)</label> <input type=\"number\" name=\"min_layer_time\" step=\"0.5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var20 string
		templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.MinLayerTime))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 157, Col: 108}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div></div></div><!-- Retraction --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Rückzug (Retraction)</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Distanz (mm)</label> <input type=\"number\" name=\"retraction_dist\" step=\"0.5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var21 string
		templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.RetractionDist))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 167, Col: 111}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Geschw. (mm/s)</label> <input type=\"number\" name=\"retraction_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var22 string
		templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.RetractionSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 171, Col: 102}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Z-Hop (mm)</label> <input type=\"number\" name=\"retraction_zhop\" step=\"0.1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var23 string
		templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.RetractionZHop))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 175, Col: 111}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Nachdrücken (mm)</label> <input type=\"number\" name=\"retraction_prime\" step=\"0.1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var24 string
		templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.RetractionPrime))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 179, Col: 113}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div></div></div><!-- Skirt & Brim --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Haftung (Skirt &amp; Brim)</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Skirt Linien</label> <input type=\"number\" name=\"skirt_count\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var25 string
		templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.SkirtCount))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 189, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Skirt Abstand</label> <input type=\"number\" name=\"skirt_offset\" step=\"0.5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var26 string
		templ_7745c5c3_Var26, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.SkirtOffset))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 193, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var26))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Brim Linien</label> <input type=\"number\" name=\"brim_count\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var27 string
		templ_7745c5c3_Var27, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.BrimCount))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 197, Col: 88}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var27))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div></div></div><!-- Machine / Advanced --><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Stützstrukturen (Support)</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Support Typ</label> <select name=\"support_type\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px; background: white;\"><option value=\"0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.SupportType == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, ">Keine</option> <option value=\"1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.SupportType == 1 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, ">Normal (Linear)</option> <option value=\"2\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.SupportType == 2 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 49, ">Tree (Stump)</option></select></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Dichte (0-1)</label> <input type=\"number\" name=\"support_density\" step=\"0.05\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var28 string
		templ_7745c5c3_Var28, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", config.SupportDensity))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 215, Col: 112}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var28))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 50, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Winkel (°)</label> <input type=\"number\" name=\"support_angle\" step=\"5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var29 string
		templ_7745c5c3_Var29, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.SupportAngle))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 219, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var29))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 51, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Z-Abstand (mm)</label> <input type=\"number\" name=\"support_z_gap\" step=\"0.1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var30 string
		templ_7745c5c3_Var30, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.SupportZGap))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 223, Col: 106}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var30))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 52, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">XY-Abstand (mm)</label> <input type=\"number\" name=\"support_xy_gap\" step=\"0.1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var31 string
		templ_7745c5c3_Var31, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.SupportXYGap))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 227, Col: 108}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var31))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 53, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Support Geschw. (mm/s)</label> <input type=\"number\" name=\"support_speed\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var32 string
		templ_7745c5c3_Var32, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.SupportSpeed))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 231, Col: 96}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var32))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 54, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Tree Ast-Durchmesser (mm)</label> <input type=\"number\" name=\"support_tree_branch_diameter\" step=\"0.5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var33 string
		templ_7745c5c3_Var33, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.SupportTreeBranchDiameter))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 235, Col: 135}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var33))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 55, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\" title=\"Durchmesser der neuen Äste am Modell\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Tree Stamm-Durchmesser (mm)</label> <input type=\"number\" name=\"support_tree_trunk_diameter\" step=\"1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var34 string
		templ_7745c5c3_Var34, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.SupportTreeTrunkDiameter))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 239, Col: 131}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var34))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 56, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\" title=\"Maximaler Durchmesser der dicken Stämme am Boden\"></div></div></div><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Raft &amp; Vasen-Modus</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Raft Schichten</label> <input type=\"number\" name=\"raft_layers\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var35 string
		templ_7745c5c3_Var35, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", config.RaftLayers))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 248, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var35))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 57, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Raft Abstand (mm)</label> <input type=\"number\" name=\"raft_offset\" step=\"0.5\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var36 string
		templ_7745c5c3_Var36, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.RaftOffset))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 252, Col: 103}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var36))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 58, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: flex; align-items: center; gap: 8px; font-size: 12px; color: #555; cursor: pointer;\"><input type=\"checkbox\" name=\"vase_mode\" value=\"true\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.VaseMode {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 59, " checked")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 60, " style=\"width: 16px; height: 16px;\"> Vasen-Modus (Spiral-Einwand)</label></div></div></div><div class=\"settings-group\" style=\"margin-bottom: 20px;\"><label style=\"display: block; font-size: 12px; font-weight: bold; color: #555; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 3px;\">Maschine &amp; Erweitert</label><div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 10px;\"><div><label style=\"display: block; font-size: 10px; color: #888;\">Düsendurchm. (mm)</label> <input type=\"number\" name=\"nozzle_diameter\" step=\"0.1\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var37 string
		templ_7745c5c3_Var37, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f", config.NozzleDiameter))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 267, Col: 111}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var37))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 61, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">G-Code Flavor</label> <select name=\"gcode_flavor\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px; background: white;\"><option value=\"0\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.GCodeFlavor == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 62, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 63, ">Marlin</option> <option value=\"1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.GCodeFlavor == 1 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 64, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 65, ">RepRap</option> <option value=\"2\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if config.GCodeFlavor == 2 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 66, " selected")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 67, ">Klipper</option></select></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Bauraum X (mm)</label> <input type=\"number\" name=\"build_volume_x\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var38 string
		templ_7745c5c3_Var38, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.BuildVolumeX))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 279, Col: 97}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var38))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 68, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div><label style=\"display: block; font-size: 10px; color: #888;\">Bauraum Y (mm)</label> <input type=\"number\" name=\"build_volume_y\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var39 string
		templ_7745c5c3_Var39, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.BuildVolumeY))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 283, Col: 97}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var39))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 69, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div><div style=\"grid-column: span 2;\"><label style=\"display: block; font-size: 10px; color: #888;\">Bauraum Z (mm)</label> <input type=\"number\" name=\"build_volume_z\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var40 string
		templ_7745c5c3_Var40, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.0f", config.BuildVolumeZ))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/viewer.templ`, Line: 287, Col: 97}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var40))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 70, "\" style=\"width: 100%; padding: 4px; border: 1px solid #ccc; border-radius: 3px; font-size: 12px;\"></div></div></div></div><div style=\"padding: 15px; border-top: 1px solid #ddd; background: #f8f9fa; display: flex; flex-direction: column; gap: 8px;\"><button type=\"submit\" id=\"slice-btn\" style=\"width: 100%; padding: 10px; background: #2196F3; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; box-shadow: 0 2px 4px rgba(0,0,0,0.1);\"><span id=\"slice-spinner\" class=\"htmx-indicator\" style=\"display:none;\">⏳ </span> Slicing starten</button> <button type=\"button\" onclick=\"exportGCode()\" style=\"width: 100%; padding: 10px; background: #4CAF50; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; box-shadow: 0 2px 4px rgba(0,0,0,0.1);\">⬇ G-Code exportieren</button><script>\n\t\t\t\tfunction exportGCode() {\n\t\t\t\t\tfetch('/export', { method: 'POST' })\n\t\t\t\t\t\t.then(resp => {\n\t\t\t\t\t\t\tif (!resp.ok) throw new Error('Export failed');\n\t\t\t\t\t\t\treturn resp.blob();\n\t\t\t\t\t\t})\n\t\t\t\t\t\t.then(blob => {\n\t\t\t\t\t\t\tconst url = URL.createObjectURL(blob);\n\t\t\t\t\t\t\tconst a = document.createElement('a');\n\t\t\t\t\t\t\ta.href = url;\n\t\t\t\t\t\t\ta.download = 'print.gcode';\n\t\t\t\t\t\t\tdocument.body.appendChild(a);\n\t\t\t\t\t\t\ta.click();\n\t\t\t\t\t\t\tdocument.body.removeChild(a);\n\t\t\t\t\t\t\tURL.revokeObjectURL(url);\n\t\t\t\t\t\t})\n\t\t\t\t\t\t.catch(err => alert('Export fehlgeschlagen: ' + err.message));\n\t\t\t\t}\n\t\t\t</script></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if paths != nil {
			templ_7745c5c3_Err = templ.JSFuncCall("setModelPath", marshal(paths)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 71, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.JSFuncCall("setSliceConfig", marshal(config)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 72, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// STLViewer renders the full page — used only on initial GET /
func STLViewer(bm *model.BaseModel, paths []model.ContinuousPath, config *model.SliceConfig) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var41 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var41 == nil {
			templ_7745c5c3_Var41 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 73, "<div id=\"viewer-root\"><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if bm == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 74, "<div class=\"stl-viewer-container\" style=\"width: 100%; height: 100%; position: relative; display: flex; align-items: center; justify-content: center; background: #2e3842; border: 1px solid #444;\"><div style=\"text-align: center; color: #aaa;\"><p style=\"font-size: 18px; margin-bottom: 10px;\">Kein Modell geladen</p><p style=\"font-size: 14px;\">Bitte laden Sie eine Datei hoch.</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 75, "<div class=\"stl-viewer-container\" style=\"width: 100%; height: 100%; position: relative; background: #1d232a; overflow: hidden; display: flex;\"><canvas id=\"stl-canvas\" style=\"display: block; flex: 1; min-width: 0; cursor: grab;\"></canvas>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = SlicerSidebar(bm, paths, config).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 76, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ.Raw(fmt.Sprintf("<script>%s</script>", viewerJs)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.JSFuncCall("setModelData", marshal(bm)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.JSFuncCall("setModelPath", marshal(paths)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.JSFuncCall("setSliceConfig", marshal(config)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 77, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
